/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PopRouteImport } from './routes/pop'
import { Route as PopReturnRouteImport } from './routes/pop-return'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SalesReturnRouteImport } from './routes/sales-return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PopRoute = PopRouteImport.update({
  id: '/pop',
  path: '/pop',
  getParentRoute: () => rootRouteImport,
} as any)
const PopReturnRoute = PopReturnRouteImport.update({
  id: '/pop-return',
  path: '/pop-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnRoute = SalesReturnRouteImport.update({
  id: '/sales-return',
  path: '/sales-return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/expenses': typeof ExpensesRoute
  '/ledger': typeof LedgerRoute
  '/pop': typeof PopRoute
  '/pop-return': typeof PopReturnRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/sales-return': typeof SalesReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/expenses': typeof ExpensesRoute
  '/ledger': typeof LedgerRoute
  '/pop': typeof PopRoute
  '/pop-return': typeof PopReturnRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/sales-return': typeof SalesReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/expenses': typeof ExpensesRoute
  '/ledger': typeof LedgerRoute
  '/pop': typeof PopRoute
  '/pop-return': typeof PopReturnRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/sales-return': typeof SalesReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/expenses'
    | '/ledger'
    | '/pop'
    | '/pop-return'
    | '/pos'
    | '/purchases'
    | '/sales'
    | '/sales-return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/expenses'
    | '/ledger'
    | '/pop'
    | '/pop-return'
    | '/pos'
    | '/purchases'
    | '/sales'
    | '/sales-return'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/expenses'
    | '/ledger'
    | '/pop'
    | '/pop-return'
    | '/pos'
    | '/purchases'
    | '/sales'
    | '/sales-return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  ExpensesRoute: typeof ExpensesRoute
  LedgerRoute: typeof LedgerRoute
  PopRoute: typeof PopRoute
  PopReturnRoute: typeof PopReturnRoute
  PosRoute: typeof PosRoute
  PurchasesRoute: typeof PurchasesRoute
  SalesRoute: typeof SalesRoute
  SalesReturnRoute: typeof SalesReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pop': {
      id: '/pop'
      path: '/pop'
      fullPath: '/pop'
      preLoaderRoute: typeof PopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pop-return': {
      id: '/pop-return'
      path: '/pop-return'
      fullPath: '/pop-return'
      preLoaderRoute: typeof PopReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-return': {
      id: '/sales-return'
      path: '/sales-return'
      fullPath: '/sales-return'
      preLoaderRoute: typeof SalesReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  ExpensesRoute: ExpensesRoute,
  LedgerRoute: LedgerRoute,
  PopRoute: PopRoute,
  PopReturnRoute: PopReturnRoute,
  PosRoute: PosRoute,
  PurchasesRoute: PurchasesRoute,
  SalesRoute: SalesRoute,
  SalesReturnRoute: SalesReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
